site_name: Network Security Resources
nav:
  - Colonial Pipeline Cyberattack: index.md
  - Emerging Threats in Network Security and Countermeasures: Emerging-threads.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/terminal
  font:
    text: Times New Roman
  features: — navigation.tabs
    — navigation.sections
    — toc.integrate
    — navigation.top
    — search.suggest
    — search.hightight
    — content.tabs.link
    — content.code.annotation
    — content.code.copy
  language: en

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rainameralkocak
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/raina-meral-kocak/

copyright: |
  &copy; 2024 <a href="https://github.com/rainameralkocak" target="_blank" rel="noopener">Raina Meral Koçak</a>
